const img = [
{id: 'casa',
icon :'<i class="fa fa-home fa-5x" aria-hidden="true"></i>'},
{id: 'lente',
icon :'<i class="fa fa-glass fa-5x"></i>'},
{id: 'user',
icon :'<i class="fa fa-user fa-5x"></i>'},
{id: 'face',
icon :'<i class="fa fa-smile-o fa-5x"></i>'},
{id: 'rocket',
icon :'<i class="fa fa-rocket fa-5x"></i>'},
{id: 'lock',
icon :'<i class="fa fa-lock fa-5x"></i>'},
{id: 'headphones',
icon :'<i class="fa fa-headphones fa-5x"></i>'},
{id: 'volume',
icon :'<i class="fa fa-volume-up fa-5x"></i>'},
{id: 'camera',
icon :'<i class="fa fa-camera fa-5x"></i>'},
{id: 'droplet',
icon :'<i class="fa fa-tint fa-5x"></i>'},
{id: 'fire',
icon :'<i class="fa fa-fire fa-5x"></i>'},
{id: 'plane',
icon :'<i class="fa fa-plane fa-5x"></i>'},
{id: 'handshake',
icon :'<i class="fa fa-handshake-o fa-5x"></i>'},
{id: 'graduation',
icon :'<i class="fa fa-graduation-cap fa-5x"></i>'},
{id: 'lemon',
icon :'<i class="fa fa-lemon-o fa-5x"></i>'},
{id: 'key',
icon :'<i class="fa fa-key fa-5x"></i>'},
{id: 'thumbtack',
icon :'<i class="fa fa-thumb-tack fa-5x"></i>'},
{id: 'gears',
icon :'<i class="fa fa-cogs fa-5x"></i>'},
{id: 'paper-plane',
icon :'<i class="fa fa-paper-plane-o fa-5x"></i>'},
{id: 'globe',
icon :'<i class="fa fa-globe fa-5x"></i>'},
{id: 'truck',
icon :'<i class="fa fa-truck fa-5x"></i>'},
{id: 'building',
icon :'<i class="fa fa-building fa-5x"></i>'},
{id: 'tree',
icon :'<i class="fa fa-tree fa-5x"></i>'},
{id: 'cutlery',
icon :'<i class="fa fa-cutlery fa-5x"></i>'},
{id: 'camera',
icon :'<i class="fa fa-camera fa-5x"></i>'},
{id: 'paint-brush',
icon :'<i class="fa fa-paint-brush fa-5x"></i>'},
{id: 'bicycle',
icon :'<i class="fa fa-bicycle fa-5x"></i>'},
{id: 'megaphone',
icon :'<i class="ffa fa-bullhorn fa-5x"></i>'},
{id: 'flask',
icon :'<i class="fa fa-flask fa-5x"></i>'}
]
